---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  copy:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: u=rw,g=r,o=r
 
#- name: install base tools and packages
- name: install tomcat
  yum:
    name:
    - httpd
    - tomcat
    state: latest

- name: create ansible tomcat directory
  file:
    path: /var/lib/tomcat/webapps/ROOT
    state: directory

- name: Write webapps/ROOT/index.html
  template:
    src: index.html.j2
    dest: /var/lib/tomcat/webapps/ROOT/index.html
    mode: 0644

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: true

- name: create ansible tomcat directory
  file:
    path: /var/lib/tomcat/webapps/ansible
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: /var/lib/tomcat/webapps/ansible/index.html

- name: enable apache httpd at boot
  service:
    name: httpd
    enabled: true
    state: started

